version: '3'

services: 

  app-node:
    build: 
      context: node
    container_name: app-node
    networks: 
      - node-network
    volumes: 
      - ./node:/usr/src/app
    tty: true
    ports: 
      - "5000:5000"
    depends_on: 
       - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks: 
      - node-network
  
  nginx:
    build: 
      context: ./nginx
    container_name: nginx
    links:
      - app-node
    depends_on:
      - app-node
    restart: always
    networks: 
      - node-network
    ports: 
      - "8080:80"

networks: 
  node-network:
    driver: bridge  